#!/bin/bash
# ------------------------------------------------------------------------------
#
# Copyright(c) vicky vergara
#
# About:
# ------
# This script:
# - Keeps the C/C++ related code with 4 spaces
# - Affects all C/C++ related code of the staged for commit files
#
#
# needs aStyle
# http://astyle.sourceforge.net/astyle.html
# ------------------------------------------------------------------------------
# To enable this hook:
# cp tools/githookis/pre-commit .git/hooks/pre-commit

set -e


# Affects all C/C++ related code of the staged for commit files
CMD="git diff --cached --name-only"

# Affects all C/C++ related code
#CMD="git ls-files"

# .c & .cpp files
C_FILES=$( $CMD | grep '\.c' | grep -v '\.cmake')
CPP_FILES=$( $CMD | grep '\.cpp' | grep -v '\.cmake')
H_FILES=$( $CMD | grep '\.h' | grep -v '\.cmake')
INL_FILES=$( $CMD | grep '\.inl')

for f in $CPP_FILES $C_FILES $H_FILES $INL_FILES
do
	echo processing $f
	astyle --attach-extern-c $f >/dev/null 2>&1
	rm -f $f.orig
	git add $f
done


if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
