/**********************************************************************
 *
 * platform.h - generated by CMake from platform.h.cmake
 *
 * GEOS - Geometry Engine Open Source
 * http://geos.osgeo.org
 *
 * Copyright (C) 2009 Mateusz Loskot
 * Copyright (C) 2005-2009 Refractions Research Inc.
 * Copyright (C) 2001-2009 Vivid Solutions Inc.
 *
 * This is free software; you can redistribute and/or modify it under
 * the terms of the GNU Lesser General Public Licence as published
 * by the Free Software Foundation.
 * See the COPYING file for more information.
 *
 *********************************************************************/

#ifndef GEOS_PLATFORM_H_INCLUDED
#define GEOS_PLATFORM_H_INCLUDED

#ifdef _MSC_VER
#ifndef NOMINMAX
#define NOMINMAX 1
#endif
#endif

/* Disable inclusion of platform.h not generated by CMake */
#define GEOS_PLATFORM_H 1

/* Set to 1 if you have stdint.h */
#cmakedefine HAVE_STDINT_H 1

/* Set to 1 if you have inttypes.h */
#cmakedefine HAVE_INTTYPES_H 1

/* Set to 1 if you have ieeefp.h */
#cmakedefine HAVE_IEEEFP_H 1

/* Set to 1 if you have `int64_t' type */
#cmakedefine HAVE_INT64_T_64 1

/* Set to 1 if `long int' is 64 bits */
#cmakedefine HAVE_LONG_INT_64 1

/* Set to 1 if `long long int' is 64 bits */
#cmakedefine HAVE_LONG_LONG_INT_64 1

/* Set to 1 if C++/C99 std::isnan is defined */
#cmakedefine HAVE_STD_ISNAN 1

/* Set to 1 if C99 isnan is defined */
#cmakedefine HAVE_ISNAN 1

/* Set to 1 if XCode __isnand is defined */
#cmakedefine HAVE_ISNAND_XCODE 1

/* Set to 1 if XCode __inline_isnand is defined */
#cmakedefine HAVE_INLINE_ISNAND_XCODE 1

/* Set to 1 if C++/C99 std::isfinite is defined */
#cmakedefine HAVE_STD_ISFINITE 1

/* Set to 1 if C99 isfinite is defined */
#cmakedefine HAVE_ISFINITE 1

/* Set to 1 if Visual C++ finite is defined */
#cmakedefine HAVE_FINITE 1

#ifdef _MSC_VER
#  define _USE_MATH_DEFINES
#endif
#include <cmath>
#include <limits>
#include <cinttypes>



#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

   typedef int64_t int64;

#if 0
/* For MingW the appropriate definitions are included in math.h
 * and float.h but the definitions in math.h are only included
 * if __STRICT_ANSI__ is not defined. Since GEOS is compiled
 * with -ansi that means those definitions are not available.
 */
#if defined(__GNUC__) && defined(_WIN32)
#include <float.h>
#endif

#ifdef HAVE_INT64_T_64
# ifdef _MSC_VER
   typedef __int64 int64;
# else
   typedef int64_t int64;
# endif
#else
# ifdef HAVE_LONG_LONG_INT_64
   typedef long long int int64;
# else
   typedef long int int64;
#  ifndef HAVE_LONG_INT_64
#   define INT64_IS_REALLY32 1
#   warning "Could not find 64bit integer definition!"
#  endif
# endif
#endif

#endif // if 0


#if defined(_MSC_VER) && _MSC_VER >= 1200 // VC++ 6.0 and above
#  include <float.h>
#  ifndef FINITE
#    define FINITE(x) _finite(x)
#  endif
#  ifndef ISNAN
#    define ISNAN(x) _isnan(x)
#  endif
#elif !defined(HAVE_IEEEFP_H)
#  include <cmath>
#  ifndef FINITE
#    define FINITE(x) std::isfinite(x)
#  endif
#  ifndef ISNAN
#    define ISNAN(x) std::isnan(x)
#  endif
#else
#  include <ieeefp.h>
#  ifndef FINITE
#    define FINITE(x) finite(x)
#  endif
#  ifndef ISNAN
#    define ISNAN(x) isnan(x)
#  endif
#endif


// Some handy constants
constexpr double DoubleNotANumber = std::numeric_limits<double>::quiet_NaN();
constexpr double DoubleMax = (std::numeric_limits<double>::max)();
constexpr double DoubleInfinity = (std::numeric_limits<double>::infinity)();
constexpr double DoubleNegInfinity = (-(std::numeric_limits<double>::infinity)());



#endif // GEOS_PLATFORM_H_INCLUDED
